version: '3.8'

services:
  rating-service:
    environment:
      - ASPNETCORE_URLS=http://+:8080  # Ensure API listens on 8080 inside Docker
    ports:
      - "5001:8080"  # Map container's 8080 to host 5001

  notification-service:
    environment:
      - ASPNETCORE_URLS=http://+:8080
    ports:
      - "5002:8080"
