name: CI Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Start Docker Compose
      run: docker compose -f docker/docker-compose.yml up -d

    - name: Wait for SQL Server to be ready
      run: |
        echo "Waiting for SQL Server to be ready..."
        sleep 5  

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: |
          8.0.x
          7.0.x
    
    - name: Restore dependencies
      run: dotnet restore src/ServiceMarketplace.sln  

    - name: Build
      run: dotnet build src/ServiceMarketplace.sln --no-restore --configuration Release 

    - name: Test Rating Service
      run: dotnet test src/RatingService/RatingService.Tests/RatingService.Tests.csproj --no-build --verbosity normal --configuration Release
      env:
        ConnectionStrings__DefaultConnection: Server=sqlserver;Database=RatingTestDb;User Id=sa;Password=YourStrong@Passw0rd;Encrypt=False;TrustServerCertificate=True;
    
    - name: Test Notification Service
      run: dotnet test src/NotificationService/NotificationService.Tests/NotificationService.Tests.csproj --no-build --verbosity normal --configuration Release
      env:
        ConnectionStrings__DefaultConnection: Server=sqlserver;Database=NotificationTestDb;User Id=sa;Password=YourStrong@Passw0rd;Encrypt=False;TrustServerCertificate=True;

    - name: Run Tests with Coverage
      run: |
        dotnet test src/ServiceMarketplace.sln --configuration Release --collect:"XPlat Code Coverage" --results-directory ./TestResults

    - name: Generate Coverage Report
      run: |
        dotnet tool install --global dotnet-reportgenerator-globaltool
        reportgenerator -reports:./TestResults/**/*.xml -targetdir:./TestResults/CoverageReport -reporttypes:Html

    - name: List Coverage Report Files
      run: ls -R ./TestResults/CoverageReport 

    - name: Upload Coverage Report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: ./TestResults/CoverageReport

    - name: Shutdown Docker Compose
      run: docker compose -f docker/docker-compose.yml down  
